version: 2.1
orbs:
  node: circleci/node@4.1
  aws-s3: circleci/aws-s3@2.0

jobs:
  tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache: 
          keys:
            - v1-dependencies-{{checksum "package.json"}}
            - v1-dependencies
      - run:
          name: "Install Dependencies"
          command: |
            yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{checksum "package.json"}}
      - run: 
          name: "Run Test"
          command: |
            yarn test

workflows:
  build_and_test:
      jobs:
        - tests
  
